language: c
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - g++-5
      - libssl-dev
    sources: &sources
      - ubuntu-toolchain-r-test

env: CXX=g++-5 CC=gcc-5

before_script:
  - git submodule update --init

script:
  - make
